[project]
name = "cctv-tg-worker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aio-pika>=9.5.8",
    "aiogram>=3.25.0",
    "faststream>=0.6.6",
    "pydantic-settings>=2.13.0",
    "python-dotenv>=1.2.1",
]
